const STR = {
  SEARCH: "Search",
  LOADING: "Loading...",
  NEW_CARD: "New Card",
  YOUR_CARDS: "Your Cards",
  MY_CARDS: "My Cards",
  CARDS: "Cards",
  TAGS: "Tags",
  ENTER_TEXT: "Enter Text",
  SIDE_B: "Side B",
  SUGGESTED: "Suggested",
  ERROR: "Error...",
  LANGUAGES: "Languages",
  NEW_TAG: "New Tag",
  ENTER_TAG: "Enter Tag",
  CREATE_TAG: " Create Tag",
  SIGN_IN_CTA: "You'll need an account to create cards",
  SIGN_IN: "Sign In",
  STUDY_MODE_ACTIVE: "(Quiz Mode)",
  DELETE_TAG_WARNING: "The tag will be deleted and removed from all cards.",
  CONFIRM_PROCEED: "Are you sure you want to proceed?",
  DELETE: "Delete",
};

export default STR;
